version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:80"
    environment:
      DB_STRING: postgresql://admin:admin@db:5432/jsp
      JWT_SECRET_KEY: fffwebgnhjy1224
      JWT_REFRESH_SECRET_KEY: ghjukuo8676653gshsh
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: jsp
