"""empty message

Revision ID: 3cafd946650a
Revises: d55a7cc83230
Create Date: 2022-06-26 21:46:51.023394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3cafd946650a'
down_revision = 'd55a7cc83230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rentals', 'quantity')
    op.add_column('reviews', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('reviews', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('reviews', 'created_at')
    op.add_column('rentals', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
