"""empty message

Revision ID: d55a7cc83230
Revises: ba36be1ccc5c
Create Date: 2022-06-26 20:17:13.873035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd55a7cc83230'
down_revision = 'ba36be1ccc5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('book_authors_author_id_fkey', 'book_authors', type_='foreignkey')
    op.drop_constraint('book_authors_book_id_fkey', 'book_authors', type_='foreignkey')
    op.create_foreign_key(None, 'book_authors', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'book_authors', 'authors', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('book_genres_book_id_fkey', 'book_genres', type_='foreignkey')
    op.drop_constraint('book_genres_genre_id_fkey', 'book_genres', type_='foreignkey')
    op.create_foreign_key(None, 'book_genres', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'book_genres', 'genres', ['genre_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('rental_books_book_id_fkey', 'rental_books', type_='foreignkey')
    op.drop_constraint('rental_books_rental_id_fkey', 'rental_books', type_='foreignkey')
    op.create_foreign_key(None, 'rental_books', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'rental_books', 'rentals', ['rental_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('reviews_book_id_fkey', 'reviews', type_='foreignkey')
    op.drop_constraint('reviews_user_id_fkey', 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key('reviews_user_id_fkey', 'reviews', 'users', ['user_id'], ['id'])
    op.create_foreign_key('reviews_book_id_fkey', 'reviews', 'books', ['book_id'], ['id'])
    op.drop_constraint(None, 'rental_books', type_='foreignkey')
    op.drop_constraint(None, 'rental_books', type_='foreignkey')
    op.create_foreign_key('rental_books_rental_id_fkey', 'rental_books', 'rentals', ['rental_id'], ['id'])
    op.create_foreign_key('rental_books_book_id_fkey', 'rental_books', 'books', ['book_id'], ['id'])
    op.drop_constraint(None, 'book_genres', type_='foreignkey')
    op.drop_constraint(None, 'book_genres', type_='foreignkey')
    op.create_foreign_key('book_genres_genre_id_fkey', 'book_genres', 'genres', ['genre_id'], ['id'])
    op.create_foreign_key('book_genres_book_id_fkey', 'book_genres', 'books', ['book_id'], ['id'])
    op.drop_constraint(None, 'book_authors', type_='foreignkey')
    op.drop_constraint(None, 'book_authors', type_='foreignkey')
    op.create_foreign_key('book_authors_book_id_fkey', 'book_authors', 'books', ['book_id'], ['id'])
    op.create_foreign_key('book_authors_author_id_fkey', 'book_authors', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###
